version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.14
      - test-1.15
jobs:
  test-1.14:
    docker:
      - image: "circleci/golang:1.14"
    steps: &ref_0
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - run: go test -benchmem -bench . ./...
      - run: go install ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test-1.15:
    docker:
      - image: "circleci/golang:1.15"
    steps: *ref_0
